### ISSUE TITLE
Player string error

### ISSUE THREAD

**Issue by tommaso-ascani** [zdwolfe/minecraft-player-notification-plugin#2]
On my webhook the plugin prints player name with this characters before or after: §4 or §r, don't know what they are, you know where the error is?

**Comment by zdwolfe** [comment]
Sorry for the delay, and sorry for the bug. Thank you for using/trying out my mod!

I'll try to make a fix if you can help me narrow down the problem. A few questions:

1. Can you please send me a screenshot, or server logs?
2. Does it happen to all players? Or just one/a few? Do those
3. What server and game version?
4. Do you have any other mods installed? Particularly those that might manipulate names (like Fakename)

**Comment by tommaso-ascani** [comment]
1. ![Immagine 2023-06-25 210619](https://github.com/zdwolfe/minecraft-player-notification-plugin/assets/31596042/35d98bdc-f0b5-4333-9392-37f416a245e9)
2. Yes it happens for all players but only on left, on join it works good.
3. Paper server, 1.20.1 (but was the same on 1.19)
4. I have LuckPerms, Essentials, Vault

I tried to look at the code but i thought you can fix it faster than me, already knowing the plugin
